---
title: "Assignment 05"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

**Out: 11/20 19:00 **  
**Due: 12/03 19:00 **  

For problem set *i*, create a script named `PS5_i.R`. Write your results briefly in a report (`Report_PS5.pdf`). Upload your **R scripts** and **report** to the `ESE5023_Assignments` repository before the deadline.

***

# Instructions  

**Collaboration:**  
Collaboration on solving the assignment is allowed, after you have thought about the problem sets on your own. It is also OK to get  clarification (but not solutions) from online resources, again after you have thought about the problem sets on your own. There are two requirements: 

* Cite your collaborators **fully and completely** (*e.g.*, “XXX explained to me what is asked in the problem set 3”). Or cite online resources (*e.g.*, “I got inspired by reading XXX”) that helped you.
* Write your scripts and report **independently** - the scripts and report must come from you only.

**Late Submission:**   
Late submissions will not receive full credit. **Half credit** will be awarded to correct solutions submitted within **24 hours** of the original deadline. Otherwise, no credit will be given. 

**Submitting your assignment:**  
Submit your scripts and report via GitHub. The submission time will be determined based on your GitHub records.  

***

# 1. Potential Renewable Energy Spots in China

In this exercise, we will search for some potential renewable energy spots in China. The data sets we will use are GeoTiff (.tif) files provided by the [WorldClim](https://worldclim.org/data/worldclim21.html).

**1.1 [5 points]** Download the following data sets and load them in R:

* Solar radiation, 2.5 minutes

* Precipitation, 2.5 minutes

* Wind speed, 2.5 minutes

**1.2 [10 points]** Plot the above data sets over China. You should make three plots, each should contain its own legend.

**1.3 [5 points]** First, let's search for regions with relatively high wind speed to build wind farms. Define a reasonable wind speed as the threshold, and describe your favorite spots.

**1.4 [5 points]** Second, let's search for regions with relatively high solar radiation and low precipitation as potential locations of photovoltaics (PV) farms. Describe your favorite spots of PV farms.

# 2. More Linux Commands

In this exercise, we will learn a few more Linux commands. For each command, please use `man` to learn what it does and how to use it correctly. First, change your directory to `~`.

(In you report, please insert of a screenshot of your Linux code and output. No need to upload R scripts for this exercise.)

**2.1 [2 points]** Make a link called `data_demo_link` to `data_demo` folder using `ln`

**2.2 [2 points]** Go to `data_demo/data/`, make an empty file `planets.txt_1st` with `touch`.

**2.3 [2 points]** Print your home directory using `echo`.

**2.4 [3 points]** Find how many files in `data_demo/data/pdb/` using `find`.

**2.5 [3 points]** Count how many `C` character appears in `data_demo/data/pdb/tnt.pdb` with `grep`.

**2.6 [2 points]** Compare `data_demo/data/pdb/ethane.pdb` and `data_demo/data/pdb/ethanol.pdb` with `diff`

**2.7 [2 points]** Check the total file size of the `data_demo` folder using `df`.

**2.8 [3 points]** Copy the `data_demo` folder to `data_demo_new`, compress it using `zip`, and decompress the `.zip` file with `unzip`.

**2.9 [3 points]** Change the file permissions flags on `data_demo_new` to `drwxr-x---` using `chmod`.

**2.10 [3 points]** Print the last 10 commands you made using `history`.

