---
title: "Lab 03"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***

# 1. More about the gapminder data

In this exercise, we will take another look at the `gapminder` data set used in [Lab 02](https://zhu-group.github.io/ese5023/Lab_02.html) by conducting a few more statistical tests. The goal is to strengthen your skills in data wrangling and statistical sleuth.

**1.1** Install the `gapminder` package if you haven't. Then load the data by:
```{r, eval=FALSE}
# Load the gapminder library
library(gapminder)
```

**1.2** Plot boxplots of the life expectancy (`lifeExp`) in 1957 for five continents side-by-side. Is there evidence that the mean life expectancies are different for different continents? 

**1.3** Repeat **1.2**, but for the different year of 2007. Compare the boxplots from **1.2** and **1.3**, which continent has witnessed the most significant improvement in mean life expectancy?

**1.4** You probably figured out that the improvement in mean life expectancy is the biggest in Asia from 1957 to 2007. Can you estimate such improvement?

**1.5** Generate a `tibble` object named `gapminder_new`, which contains mean life expectancy (`mean_lifeExp`) and mean GDP per capita (`mean_gdpPercap`) in each country; both are averaged from 1957 to 2007. Plot a scatter plot with `mean_lifeExp` as the Y-axis and `mean_lifeExp` as the X-axis. 

**1.6** Based on the scatter plot from **1.5**, can we fit a simple linear regression model to the two variables? Why or why not?

**1.7** Fitting a simple linear regression model requires linearity between the two variables. Apparently, such an assumption is not met by examining the scatter plot from **1.6**. This is because `mean_gdpPercap` does not follow a normal distribution. Instead it follows a *log-normal distribution*. The log-normal distribution is characterized with a long tail towards high values. In statistics, this is called *positively skewed* or *right-skewed*. Use the `hist()` function to verify `mean_gdpPercap` indeed has a long tail. Please notice that environmental data often follow log-normal distributions.

**1.8** We can transfer a log-normal distribution to a normal distribution using logarithmic calculations. Now take `log` on `mean_gdpPercap`, and add the results to `gapminder_new` as a new variable `mean_gdpPercap_log` using the `mutate()` function. Check the distribution of `mean_gdpPercap_log`.

**1.9** Plot a scatter plot with `mean_lifeExp` as the Y-axis and `mean_gdpPercap_log` as the X-axis. Compare it with that from **1.5**, describe the differnece between the two.

**1.10** As both `mean_gdpPercap_log` and `mean_lifeExp` are roughly following normal distributions now, we can finally build a linear model between `mean_lifeExp` and `mean_gdpPercap_log`. Fit a simple linear regression model between `mean_lifeExp` and `mean_gdpPercap_log`, and add the regression line to the scatter plot from **1.9**. Estimate the improvement in life expectancy when GDP per capita doubles.

**1.11**  Split `gapminder_new` into two subsets - `gapminder_new_train` (with 85% of the total data points) and `gapminder_new_test` (with 15% of the total data points). Following **1.10**, build a linear model (named `model_log`) between `mean_gdpPercap_log` and `mean_lifeExp` using data from `gapminder_new_train` subset. 

**1.12** Apply the fitted linear model `model_log` to `gapminder_new_test` subset, get predicted life expectancies using the `predict()` function. Compare predicted life expectancies with actual values in `gapminder_new_test` in terms of correlation coefficients and relative mean bias. 

# 2. Transforming data to normal distribution

Parametric methods, such as t-test, ANOVA tests, and linear regression, assume that the dependent (outcome) variable is approximately normally distributed for every groups to be compared. Read [Transform Data to Normal Distribution in R](https://www.datanovia.com/en/lessons/transform-data-to-normal-distribution-in-r/) and [Summary and Analysis of Extension Program Evaluation in R](http://rcompanion.org/handbook/I_12.html) for how to do this in R.
