---
title: "Lab 04 `Pandas` and time series"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***

# 1. `Pandas` data analysis practice

In this assignment, we will practice some of the concepts and skills covered [Section 06](https://zhu-group.github.io/ese5023/Section_06.html). 

**1.** Download the [demo file](https://zhu-group.github.io/ese5023/download/countries.csv) contains basic information of world countries, read it as dataframe `countries_df`.

**2.** How many countries does the dataframe contain? 

[Hint: Use the `.shape` method]

**3.** Retrieve a list of continents from the dataframe?

[Hint: Use the `.unique` method of a series]

**4.** What is the total population of all the countries listed in this dataset?

**5.** What is the overall life expectancy across the world?

[Hint: You'll need to take a weighted average of life expectancy using populations as weights]

**6.** Create a dataframe containing `10` countries with the highest population.

**7.** Add a new column in `countries_df` to record the overall GDP per country.

**8.** Create a dataframe containing `10` countries with the lowest GDP per capita, among the counties with a population greater than `100` million.

**9.** Create a dataframe that counts the number of countries in each continent?

**10.** Create a dataframe showing the total population of each continent.

**11.** Let's download [another CSV file](https://zhu-group.github.io/ese5023/download/covid-countries-data.csv) containing overall COVID-19 stats for various countries, and read the data into another `pandas` dataframe `covid_data_df`.

**12.** Count the number of countries for which the `total_tests` data is missing.

[Hint: Use the `.isna` method]

**13.** Let's merge the two dataframes (`countries_df` and `covid_data_df`) on the `location` column, and name the merged dataframe `combined_df`

[Hint: Use the `.merge` method on `countries_df`. Search how to use `.merge` by yourself]

**14.** Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.

**15.** Create a dataframe with `10` counties that have the highest number of tests per million people.

**16.** Create a dataframe with `10` counties that have the highest number of cases per million people.

**17.** Count number of countries that feature in both the lists of "highest number of tests per million" (from question #15) and "highest number of cases per million" (from question #16).

[Hint: Use the `.merge` method again]

**18.** Count number of countries that feature in both the lists "`20` countries with the lowest GDP per capita" and "`20` countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than `10` million while creating the list.

***

# 2. Basics of time series

In `Anaconda Powershell`, install `seaborn`:

```{python, eval=F}
pip install seaborn
```

**1.** Read the [daily ozone data file](https://zhu-group.github.io/ese5023/download/ozone_data.csv) we used in [Section 06](https://zhu-group.github.io/ese5023/Section_06.html#Exercise_4). Read the data as `ozone_data` dataframe.

**2.** Create a new column `cDate` that contains string values in a format like `2020-05-01`. Here we use `2020` as the year of all observations.

[Hint: Use the `.astype` method to convert formats, and `+` to combine strings]

**3.** Create a new column `Date`, where you convert `cDate` to `Date` with `to_datetime` method. By doing so, we convert `string` to `Timestamp`. See [this](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html) for more about `Timestamp`.

**4.** Create a time series by apply `ozone_data.set_index('Date')`.

**5.** By far, we have created a time series. We will take a further look at how to analyze time series in the future. For now, simply type:

```{python, eval=F}
ozone['Ozone'].plot()
```

You will get a ozone time series. For a plot with several panels, run:

```{python, eval=F}
# Import modules
import matplotlib.pyplot as plt
import seaborn as sns

# Columns to plot
cols_plot = ['Ozone', 'Temperature', 'Wind.Speed']
axes = ozone[cols_plot].plot(marker='.', linestyle='None', figsize=(11, 9), subplots=True)
axes[0].set_ylabel('Ozone (ppb)')
axes[1].set_ylabel('Temperature (F)')
axes[2].set_ylabel('Wind Speed (m/s)')
```
