---
title: "Section 15 Making websites with R Markdown"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

> “Create a website that expresses something about who you are that won't fit into the template available to you on a social networking site.” - Jaron Lanier

***

# R Markdown

[R Markdown](https://rmarkdown.rstudio.com/) is a file format for making dynamic documents with R. An R Markdown document is written in markdown (an easy-to-write plain text format) and contains chunks of embedded code. R Markdown files are designed to be used with the `rmarkdown` package. `rmarkdown` comes installed with the RStudio IDE.

R Markdown provides an authoring framework for data science. You can use a single R Markdown file to both
+ save and execute code
+ generate high quality reports that can be shared with an audience

R Markdown documents are fully reproducible and support dozens of static and dynamic output formats. In this section, we will learn how to convert an R Markdown file into `html` files.

***

# Building a website

## 1. Making a repository on Github

+ Open GitKraken, make a new repository `web_test` by clicking `Start a hosted repo`, then fill the information, and save this repository locally (e.g., `C://web_test`).

+ Download [this demo](https://zhu-group.github.io/ese5023/download/web_demo.zip), decompress it, and copy all items (including files and folders) to the local repository folder.

+ Stage and commit all changes, and push the repository to Github.

## 2. Home page

Each website requires a `.Rmd` file named `index.Rmd`, which provides the content for the home page of your website. Take the demo as an example, the `index.Rmd` provides basic description of the website.  

```{bash, eval=F}
---
title: "My Website"
output:
  html_document:
    df_print: paged
---

Welcome to my website!  
I am a student at SUSTech, my research area is about xxx.
```

Here line 1-6 means that the output file will be in `html` format. And line 8-9 can be replaced by real information.

## 3. Global YAML header

Another necessary file is `_site.yml`, which provides the global YAML header for the whole site. In the demo, the `_site.yml` is written as:

```{bash, eval=F}
name: "My Website"
output_dir: "docs"  # docs directory of master branch
navbar:
  title: "xxx's website"
  type: inverse
  left:
    - text: "Home"
      href: index.html
    - text: "Page1"
      href: Page1.html
    - text: "Page2"
      href: Page2.html
    - text: "Page3"
      href: Page3.html      
    - text: "Page4"
      menu:
        - text: "Page4.1"
          href: Page4.1.html
        - text: "Page4.2"
          href: Page4.2.html
        - text: "Page4.3"
          href: Page4.3.html   
output:
  html_document:
    theme: cerulean
    highlight: pygments
    
```

Here we define a home page with `index.Rmd`. `Page1` to `Page2` are static pages, and `Page4` has a drop-down menu. 

`theme` specifies the (Bootstrap)[https://bootswatch.com/3/] theme to use for the page (themes are drawn from the Bootswatch theme library). Valid themes include:  

+ default
+ cerulean
+ journal
+ flatly
+ readable
+ spacelab
+ united
+ cosmo
+ lumen
+ paper
+ sandstone
+ simplex
+ yeti

You can check the above themes at this [gallery](https://www.datadreaming.org/post/r-markdown-theme-gallery/). Pass null for no theme (in this case you can use the `css` parameter to add your own styles). 

`highlight` specifies the syntax highlighting style. Supported styles include:  

+ default
+ tango
+ pygments
+ kate
+ monochrome
+ espresso
+ zenburn
+ haddock
+ breezedark
+ textmate. 

Pass null to prevent syntax highlighting.

More about `_site.yml` can be found [here](http://rmarkdown.rstudio.com/html_document_format.html#appearance_and_style).

## 4. Markdown Syntax

See `Page1.Rmd` for basic syntax in R Markdown. More are available at this [R Markdown cheat sheet](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf).  

## 5. Build a site

You can check the current page by clicking `Knit`, a new window will pop up to show the `html` file.

Finally, when everything looks fine, set working directory to local repository. In R console, run:

```{bash, eval=F}
rmarkdown::render_site()
```

In the demo, a website (and all `html` files) will be created in `docs/`. New your website is ready to be launched.

***

# Publish the website on Github

Go to Github:

+ Open the remote repository on Github
+ Click `Settings`  
+ under `GitHub Pages` section, use `main` branch and `/docs` folder.

Open GitKraken, stage and commit all changes. And wait for a few minutes as Github is publishing the website. 

You should be able to view your website at: `https://xxx.github.io/web_test/`, where `xxx` is your Github user name.

*** 

# General workflow

+ **Step 1:** Make changes to source files (`.Rmd`)

+ **Step 2:** Check with `knit`

+ **Step 3:** Re-build the whole site with `rmarkdown::render_site()`

+ **Step 4:** Stage and commit with GitKraken

+ **Step 5:** Push with GitKraken, and wait for a few minutes. If you get an error message email from Github, go back to Step 1-4, fix the bug, and push again.

***

# In-class exercises

## Exercise #1

Launch your own website. When it's ready, share it with the class. 

***

# Further reading

* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

* [Making free websites with RStudio’s R Markdown](https://jules32.github.io/rmarkdown-website-tutorial/index.html)

* [Introduction to R Markdown](https://rmarkdown.rstudio.com/articles_intro.html)

* [R Markdown Cheat Sheet](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)

* [R Markdown Websites](https://rmarkdown.rstudio.com/lesson-13.html)

* [R Markdown Websites](https://garrettgman.github.io/rmarkdown/rmarkdown_websites.html)
