<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Section 07 Statistical sleuth: Intermediate</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Computing and Programming for Environmental Research</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Syllabus.html">
    <span class="fa fa-bell-o"></span>
     
    Syllabus
  </a>
</li>
<li>
  <a href="Schedule.html">
    <span class="fa fa-calendar"></span>
     
    Schedule
  </a>
</li>
<li>
  <a href="Resource.html">
    <span class="fa fa-wrench"></span>
     
    Resource
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-laptop"></span>
     
    Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Assignment_01.html">Assignment 01</a>
    </li>
    <li>
      <a href="Assignment_02.html">Assignment 02</a>
    </li>
    <li>
      <a href="Assignment_03.html">Assignment 03</a>
    </li>
    <li>
      <a href="Assignment_04.html">Assignment 04</a>
    </li>
    <li>
      <a href="Assignment_05.html">Assignment 05</a>
    </li>
    <li>
      <a href="Assignment_06.html">Assignment 06</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Section 07 Statistical sleuth: Intermediate</h1>

</div>


<blockquote>
<p>“Models should be as simple as possible, but not more so.” - Albert Einstein</p>
</blockquote>
<div id="anova" class="section level1">
<h1>ANOVA</h1>
<p>Analysis of Variance (ANOVA) is a statistical technique, commonly used to study differences between two or more group means. ANOVA test is centred on the different sources of variation in a typical variable. ANOVA in R primarily provides evidence of the existence of the mean equality between the groups. This statistical method is an extension of the t-test. It is used in a situation where the factor variable has more than one group. <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div id="one-way-anova" class="section level2">
<h2>One-way ANOVA</h2>
<p>There are many situations where you need to compare the mean between <strong>multiple groups</strong>. For instance, you may want to know the concentration of a certain chemical under 3 different treatments. The ANOVA test can tell if the 3 groups have similar concentration.</p>
<p>To clarify if the data comes from the same population, you can perform a <strong>one-way</strong> analysis of variance (one-way ANOVA hereafter). This test, like any other statistical tests, gives evidence whether the <em>H0</em> hypothesis can be accepted or rejected.</p>
<p>Hypothesis in one-way ANOVA test:</p>
<ul>
<li>Null hypothesis (H0): <strong>The means between groups are identical</strong></li>
<li>Alternative hypothesis: <strong>At least, the mean of one group is different</strong></li>
</ul>
<p>In other words, the H0 hypothesis implies that there is <strong>not enough evidence</strong> to prove the mean of the group (factor) are different from another. This test is similar to the <em>t-test</em>, although ANOVA test is recommended in a situation with more than 2 groups.</p>
<p>Let’s use the <a href="https://zhu-group.github.io/ese5023/download/crop.data.csv">crop dataset</a> to implement the one-way ANOVA test. The dataset contains 96 rows and 4 variables:</p>
<ul>
<li><code>yield</code>: crop yield</li>
<li><code>density</code>: type of soil density: factor level: 1 and 2</li>
<li><code>block</code>: blocking method used: factor level: 1, 2, 3, and 4</li>
<li><code>fertilizer</code>: type of fertilizer used: factor level: 1, 2, and 3</li>
</ul>
<p>In R import the data:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="co"># Read csv</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>crop_data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;crop.data.csv&quot;</span>, <span class="dt">header=</span>T)</span>
<span id="cb1-7"><a href="#cb1-7"></a></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co"># Change to factor type</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>crop_data_tbl &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(crop_data) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">fertilizer =</span> <span class="kw">factor</span>(fertilizer, <span class="dt">ordered =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">block =</span> <span class="kw">factor</span>(block, <span class="dt">ordered =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">density =</span> <span class="kw">factor</span>(density, <span class="dt">ordered =</span> <span class="ot">TRUE</span>))   </span>
<span id="cb1-13"><a href="#cb1-13"></a></span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="co"># Quick check</span></span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="kw">glimpse</span>(crop_data_tbl)</span></code></pre></div>
<pre><code>## Rows: 96
## Columns: 4
## $ density    &lt;ord&gt; 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, ...
## $ block      &lt;ord&gt; 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, ...
## $ fertilizer &lt;ord&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
## $ yield      &lt;dbl&gt; 177.2287, 177.5500, 176.4085, 177.7036, 177.1255, 176.7783, 176.7463, 177.0612, 176.2749, 177.9672, 176.6013, 177.0305, 177.4795, 176.8741, 176.1144, 176.0084, 176.1083, 178....</code></pre>
<p>Our objective is to test the following assumption:</p>
<ul>
<li>Null: There is <strong>no difference</strong> in crop yield average among fertilizer groups</li>
<li>Alternative: The crop yield average is different for <strong>at least</strong> one fertilizer group.</li>
</ul>
<p>In other words, we want to know if there is a statistical difference between the mean of the crop yeild according to the type of fertilizer.</p>
<p>First, we can check the level of the fertilizer with the following code:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw">levels</span>(crop_data_tbl<span class="op">$</span>fertilizer)</span></code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot;</code></pre>
<p>We can compute the mean and standard deviation:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>crop_data_tbl <span class="op">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="st">  </span><span class="kw">group_by</span>(fertilizer) <span class="op">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb5-4"><a href="#cb5-4"></a>    <span class="dt">count =</span> <span class="kw">n</span>(),</span>
<span id="cb5-5"><a href="#cb5-5"></a>    <span class="dt">mean_yield =</span> <span class="kw">mean</span>(yield, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb5-6"><a href="#cb5-6"></a>    <span class="dt">sd_yield =</span> <span class="kw">sd</span>(yield, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb5-7"><a href="#cb5-7"></a>  )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 3 x 4
##   fertilizer count mean_yield sd_yield
##   &lt;ord&gt;      &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1 1             32       177.    0.685
## 2 2             32       177.    0.574
## 3 3             32       177.    0.599</code></pre>
<p>We can also graphically check if there is a difference between the distribution:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="kw">ggplot</span>(crop_data_tbl, <span class="kw">aes</span>(<span class="dt">x =</span> fertilizer, <span class="dt">y =</span> yield, <span class="dt">fill =</span> fertilizer)) <span class="op">+</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<p><img src="Section_07_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Finally, we run the one-way ANOVA test with the command <code>aov</code>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>anova_one_way &lt;-<span class="st"> </span><span class="kw">aov</span>(yield <span class="op">~</span><span class="st"> </span>fertilizer, <span class="dt">data =</span> crop_data_tbl)</span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="kw">summary</span>(anova_one_way)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## fertilizer   2   6.07  3.0340   7.863  7e-04 ***
## Residuals   93  35.89  0.3859                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value is lower than the usual threshold of 0.05. You are confident to say there is a statistical difference between the groups, indicated by the "***".</p>
</div>
<div id="pairwise-comparison" class="section level2">
<h2>Pairwise comparison</h2>
<p>The one-way ANOVA test does not inform which group has a different mean. Instead, you can perform a <em>Tukey test</em> with the function <code>TukeyHSD()</code>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="kw">TukeyHSD</span>(anova_one_way)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = yield ~ fertilizer, data = crop_data_tbl)
## 
## $fertilizer
##          diff         lwr       upr     p adj
## 2-1 0.1761687 -0.19371896 0.5460564 0.4954705
## 3-1 0.5991256  0.22923789 0.9690133 0.0006125
## 3-2 0.4229569  0.05306916 0.7928445 0.0208735</code></pre>
</div>
<div id="two-way-anova" class="section level2">
<h2>Two-way ANOVA</h2>
<p>A two-way ANOVA test adds another group variable to the formula. It is identical to the one-way ANOVA test. Hypothesis in two-way ANOVA test:</p>
<ul>
<li>Null: The means are equal for both variables (i.e., factor variable)</li>
<li>Alternative: The means are different for both variables</li>
</ul>
<p>Let’s add <code>block</code> variable to the model. This variable indicates the blocking method used in the land. Now we are interested to see if there is a statistical dependence between the fertilizer type (<code>fertilizer</code>) and blocking method (<code>block</code>).</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>anova_two_way &lt;-<span class="st"> </span><span class="kw">aov</span>(yield <span class="op">~</span><span class="st"> </span>fertilizer <span class="op">+</span><span class="st"> </span>block, <span class="dt">data =</span> crop_data_tbl)</span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="kw">summary</span>(anova_two_way)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## fertilizer   2  6.068  3.0340   9.018 0.000269 ***
## block        3  5.608  1.8693   5.556 0.001522 ** 
## Residuals   90 30.278  0.3364                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can conclude that both fertilizer type (<code>fertilizer</code>) and blocking method (<code>block</code>) are statistically different from 0. We can reject the Null hypothesis and confirm that changing the fertilizer type <strong>or</strong> the blocking method impact the crop yeilds.</p>
</div>
</div>
<div id="multiple-linear-regression" class="section level1">
<h1>Multiple Linear Regression</h1>
<p>We have used the simple linear regression model in the last section, where we assume a linear relationship between a <em>response variable</em> and a single <em>predictor variable</em>. However, it is rarely the case that a dataset will have a single predictor variable. It is also rarely the case that a response variable will only depend on a single variable. So in this chapter, we will extend our current linear model to allow a response to depend on <strong>multiple</strong> predictors.</p>
<p>Let’s use the <code>airquality</code> dataset from the <code>datasets</code> package that comes with R. The dataset contains daily ozone concentration, solar radiation, wind speed, and temperature in New York City from May to September. Load the <code>airquality</code> by:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="kw">library</span>(datasets)</span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="kw">library</span>(stats)</span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="kw">data</span>(airquality)</span></code></pre></div>
<p>Check the data by</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="kw">str</span>(airquality)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    153 obs. of  6 variables:
##  $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...
##  $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...
##  $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
##  $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...
##  $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
##  $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
<p>Now we will focus on using three variables, <code>Solar.R</code>, <code>Wind</code>, and <code>Temp</code>, as predictor variables. That is, we would like to model the ozone contraction as a function of solar radiation, wind speed, and temperature. To do so, we will define the following linear model:</p>
<p><span class="math display">\[y_{i}  = \beta_{0} + \beta_{1}x_{i1} + \beta_{2}x_{i2} + \beta_{3}x_{i3} + \epsilon_{i},  i = 1,2,3,...,n\]</span></p>
<p>where <span class="math inline">\(\epsilon_{i}\)</span> ~ <span class="math inline">\(N(0, \sigma^{2})\)</span>. In this notation, we will define:</p>
<ul>
<li><span class="math inline">\(x_{i1}\)</span> as the solar radiation (<code>Solar.R</code>) of the <em>i</em>th day.</li>
<li><span class="math inline">\(x_{i2}\)</span> as the wind speed (<code>Wind</code>) of the <em>i</em>th day.</li>
<li><span class="math inline">\(x_{i3}\)</span> as the temperature (<code>Temp</code>) of the <em>i</em>th day.</li>
</ul>
<p>The data points (<span class="math inline">\(x_{i1}, x_{i2}, x_{i3}, y_{i}\)</span>) now exist in 4-dimensional space, so instead of fitting a line as we did in the simple linear regression model to the data, we will fit a 3-dimensional space.</p>
<p>Before the linear regression model can be applied, one must verify multiple factors and make sure assumptions are met. Most of all, one must make sure <em>linearity</em> exists between the variables in the dataset. One of the fastest ways to check the linearity is by using scatter plots.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># plotting the data to determine the linearity</span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="kw">plot</span>(airquality, <span class="dt">main=</span><span class="st">&quot;Matrix Scatterplot&quot;</span>)</span></code></pre></div>
<p><img src="Section_07_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>From the above scatter plot we can determine the variables <code>Ozone</code>, <code>Solar.R</code>, <code>Wind</code>, and <code>Temp</code> in the database <code>airquality</code> are in linearity.</p>
<p>In R, the multiple linear regression is done as:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>model &lt;-<span class="st"> </span><span class="kw">lm</span>(Ozone <span class="op">~</span><span class="st"> </span>Wind <span class="op">+</span><span class="st"> </span>Temp <span class="op">+</span><span class="st"> </span>Solar.R, <span class="dt">data =</span> airquality)</span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="kw">coef</span>(model)</span></code></pre></div>
<pre><code>##  (Intercept)         Wind         Temp      Solar.R 
## -64.34207893  -3.33359131   1.65209291   0.05982059</code></pre>
<p><span class="math display">\[y_{i}  = -64.34 + -3.33x_{i1} + 1.65x_{i2} + 0.060x_{i3}\]</span> Here we have fitted our model using <code>lm()</code>, however, we have introduced a new syntactical element. The formula <code>Ozone ~ Wind + Temp + Solar.R</code> reads: “model the response variable <code>Ozone</code> as a linear function of <code>Wind</code>, <code>Temp</code>, and <code>Solar.R</code>”. That is, it will estimate an intercept, as well as slope coefficients for <code>Wind</code>, <code>Temp</code>, and <code>Solar.R</code>. We then extract these as we have done before using <code>coef()</code>.</p>
<p>The model can be further explored with the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="kw">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Wind + Temp + Solar.R, data = airquality)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.485 -14.219  -3.551  10.097  95.619 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -64.34208   23.05472  -2.791  0.00623 ** 
## Wind         -3.33359    0.65441  -5.094 1.52e-06 ***
## Temp          1.65209    0.25353   6.516 2.42e-09 ***
## Solar.R       0.05982    0.02319   2.580  0.01124 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.18 on 107 degrees of freedom
##   (42 observations deleted due to missingness)
## Multiple R-squared:  0.6059, Adjusted R-squared:  0.5948 
## F-statistic: 54.83 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the above model, we assume that all the predictor variables are <strong>independent</strong> of each other. However, such assumption is falwed as we can see from the Matrix Scatterplot that <code>Temp</code> corrlates with <code>Wind</code>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="kw">cor</span>(airquality<span class="op">$</span>Wind, airquality<span class="op">$</span>Temp)</span></code></pre></div>
<pre><code>## [1] -0.4579879</code></pre>
<p>Such <strong>interaction variables</strong> introduce an additional level of regression analysis by allowing researchers to explore the synergistic effects of combined predictors. In R, you can interact two variables by using a colon <code>:</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Ozone <span class="op">~</span><span class="st"> </span>Wind <span class="op">+</span><span class="st"> </span>Temp <span class="op">+</span><span class="st"> </span>Solar.R <span class="op">+</span><span class="st"> </span>Wind<span class="op">:</span>Temp, <span class="dt">data =</span> airquality)</span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="kw">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Wind + Temp + Solar.R + Wind:Temp, data = airquality)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.888 -11.938  -3.084   8.753  94.235 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -245.08368   46.84632  -5.232 8.53e-07 ***
## Wind          14.38471    4.13249   3.481 0.000727 ***
## Temp           3.91373    0.57217   6.840 5.26e-10 ***
## Solar.R        0.06599    0.02152   3.067 0.002745 ** 
## Wind:Temp     -0.22795    0.05259  -4.334 3.34e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.61 on 106 degrees of freedom
##   (42 observations deleted due to missingness)
## Multiple R-squared:  0.6652, Adjusted R-squared:  0.6526 
## F-statistic: 52.66 on 4 and 106 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Indeed the interaction term has a signiicant slope, so you may want to include this term in your linear model.</p>
<hr />
</div>
<div id="overfitting-in-regression-model" class="section level1">
<h1>Overfitting in Regression Model</h1>
<p>Overfitting a regression model occurs when you <strong>attempt to estimate too many parameters from a sample that is too small</strong>. Regression analysis uses one sample to estimate the values of the coefficients for all of the terms in the equation. The sample size limits the number of terms that you can safely include before you begin to overfit the model.</p>
<p>Larger sample sizes allow you to specify more complex models. For trustworthy results, your sample size must be <strong>large enough</strong> to support the level of complexity that is required by your research question. If your sample size isn’t large enough, you won’t be able to fit a model that adequately approximates the true model for your response variable. You won’t be able to trust the results.</p>
<p>You must have a sufficient number of observations for each term in a regression model. Simulation studies show that a good rule of thumb is to have <strong>10-15 observations per term</strong> in multiple linear regression. For example, if your model contains two predictors and the interaction term, you’ll need 30-45 observations. However, if the effect size is small or there is high multicollinearity, you may need more observations per term. <a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<p>Let’s demonstrate the idea by adding more fake variables to the linear model.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>N              &lt;-<span class="st"> </span><span class="kw">dim</span>(airquality)[<span class="dv">1</span>]</span>
<span id="cb27-2"><a href="#cb27-2"></a>Fake           &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dt">dim=</span><span class="kw">c</span>(N,<span class="dv">10</span>))</span>
<span id="cb27-3"><a href="#cb27-3"></a>airquality_new &lt;-<span class="st"> </span>airquality</span>
<span id="cb27-4"><a href="#cb27-4"></a></span>
<span id="cb27-5"><a href="#cb27-5"></a><span class="co"># Generate some fake observations</span></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>){</span>
<span id="cb27-7"><a href="#cb27-7"></a>  Fake[,i]     &lt;-<span class="st"> </span><span class="kw">rnorm</span>(N, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb27-8"><a href="#cb27-8"></a>}</span>
<span id="cb27-9"><a href="#cb27-9"></a></span>
<span id="cb27-10"><a href="#cb27-10"></a><span class="co"># Attach to the original data</span></span>
<span id="cb27-11"><a href="#cb27-11"></a>airquality_new &lt;-<span class="st"> </span><span class="kw">cbind</span>(airquality,Fake)</span>
<span id="cb27-12"><a href="#cb27-12"></a>airquality_new &lt;-<span class="st"> </span>airquality_new[<span class="dv">1</span><span class="op">:</span><span class="dv">15</span>,]</span>
<span id="cb27-13"><a href="#cb27-13"></a></span>
<span id="cb27-14"><a href="#cb27-14"></a><span class="co"># Change column names</span></span>
<span id="cb27-15"><a href="#cb27-15"></a><span class="kw">colnames</span>(airquality_new)[<span class="dv">7</span><span class="op">:</span><span class="dv">16</span>] =<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;Fake&quot;</span>,<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">10</span>),<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb27-16"><a href="#cb27-16"></a></span>
<span id="cb27-17"><a href="#cb27-17"></a><span class="co"># Fit linear model</span></span>
<span id="cb27-18"><a href="#cb27-18"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(Ozone <span class="op">~</span><span class="st"> </span>Fake1 <span class="op">+</span><span class="st"> </span>Fake2 <span class="op">+</span><span class="st"> </span>Fake3 <span class="op">+</span><span class="st"> </span>Fake4 <span class="op">+</span><span class="st"> </span>Fake5 <span class="op">+</span><span class="st"> </span></span>
<span id="cb27-19"><a href="#cb27-19"></a><span class="st">            </span>Fake6 <span class="op">+</span><span class="st"> </span>Fake7 <span class="op">+</span><span class="st"> </span>Fake8 <span class="op">+</span><span class="st"> </span>Fake9 <span class="op">+</span><span class="st"> </span>Fake10, <span class="dt">data =</span> airquality_new)</span>
<span id="cb27-20"><a href="#cb27-20"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Fake1 + Fake2 + Fake3 + Fake4 + Fake5 + 
##     Fake6 + Fake7 + Fake8 + Fake9 + Fake10, data = airquality_new)
## 
## Residuals:
##       1       2       3       4       6       7       8       9      11      12      13      14      15 
##  1.6027 -1.1241  0.9664 -2.6742 -0.1686  1.8985  0.7300  0.3051  0.6076 -0.4638 -0.3675 -1.6641  0.3521 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   31.827      1.644  19.356  0.00266 **
## Fake1          7.619      1.425   5.346  0.03325 * 
## Fake2         46.450      5.453   8.518  0.01351 * 
## Fake3         25.162      3.299   7.626  0.01676 * 
## Fake4        -16.359      2.959  -5.528  0.03120 * 
## Fake5         -3.411      1.450  -2.352  0.14296   
## Fake6         12.455      2.063   6.037  0.02636 * 
## Fake7         15.829      1.926   8.220  0.01448 * 
## Fake8        -30.181      3.912  -7.714  0.01639 * 
## Fake9          3.444      1.210   2.847  0.10440   
## Fake10        13.315      1.525   8.734  0.01286 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.146 on 2 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.9846, Adjusted R-squared:  0.9074 
## F-statistic: 12.76 on 10 and 2 DF,  p-value: 0.07479</code></pre>
<p>You can see the high <span class="math inline">\(R^{2}\)</span> doesn’t make any sense, as the linear model has no valid observations.</p>
<hr />
</div>
<div id="variable-selection" class="section level1">
<h1>Variable Selection</h1>
<p>We use Boston Housing Data as an illustrative example. Boston housing data is a built-in dataset in <code>MASS</code> package, so you do not need to download externally. Package <code>MASS</code> comes with R when you installed R, so <strong>no need</strong> to use <code>install.packages(MASS)</code> to download and install, but you do need to load this package. <a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="kw">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="kw">data</span>(Boston); <span class="co">#this data is in MASS package</span></span>
<span id="cb32-2"><a href="#cb32-2"></a><span class="kw">str</span>(Boston)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    506 obs. of  14 variables:
##  $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
##  $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
##  $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
##  $ chas   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
##  $ rm     : num  6.58 6.42 7.18 7 7.15 ...
##  $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
##  $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
##  $ rad    : int  1 2 2 3 3 3 5 5 5 5 ...
##  $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
##  $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
##  $ black  : num  397 397 393 395 397 ...
##  $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
##  $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...</code></pre>
<p>The original data are 506 observations on 14 variables, <code>medv</code> being the response variable <em>y</em>.</p>
<p>We usually split our data to training and testing samples. In this case, we sample 90% of the original data and use it as the <em>training set</em>. The remaining 10% is used as <em>test set</em>. The regression model will be built on the training set, and future performance of your model will be evaluated with the test set.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>sample_index &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(Boston),<span class="kw">nrow</span>(Boston)<span class="op">*</span><span class="fl">0.90</span>)</span>
<span id="cb34-2"><a href="#cb34-2"></a>Boston_train &lt;-<span class="st"> </span>Boston[sample_index,]</span>
<span id="cb34-3"><a href="#cb34-3"></a>Boston_test  &lt;-<span class="st"> </span>Boston[<span class="op">-</span>sample_index,]</span></code></pre></div>
<p>What we want to do next is to build a <strong>best</strong> model with training data. Let’s begin with including all <em>x</em> variables in the model:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>model_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(medv<span class="op">~</span>crim<span class="op">+</span>zn<span class="op">+</span>chas<span class="op">+</span>nox<span class="op">+</span>rm<span class="op">+</span>dis<span class="op">+</span>rad<span class="op">+</span>tax<span class="op">+</span>ptratio<span class="op">+</span>black<span class="op">+</span>lstat, <span class="dt">data=</span>Boston_train)</span></code></pre></div>
<p>To include all variables in the model, you can write the statement this simpler way.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>model_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>Boston_train)</span>
<span id="cb36-2"><a href="#cb36-2"></a><span class="kw">summary</span>(model_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ ., data = Boston_train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.8577  -2.6213  -0.5244   1.8967  26.0150 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  31.493978   5.214160   6.040 3.28e-09 ***
## crim         -0.109660   0.032290  -3.396 0.000745 ***
## zn            0.046470   0.014156   3.283 0.001110 ** 
## indus         0.018104   0.062018   0.292 0.770483    
## chas          2.220435   0.867321   2.560 0.010796 *  
## nox         -17.000459   3.843053  -4.424 1.22e-05 ***
## rm            4.523964   0.433540  10.435  &lt; 2e-16 ***
## age          -0.011063   0.013461  -0.822 0.411634    
## dis          -1.508704   0.204606  -7.374 8.28e-13 ***
## rad           0.273376   0.066832   4.091 5.12e-05 ***
## tax          -0.012067   0.003762  -3.208 0.001435 ** 
## ptratio      -0.956742   0.131079  -7.299 1.36e-12 ***
## black         0.009769   0.002722   3.589 0.000369 ***
## lstat        -0.432628   0.052339  -8.266 1.64e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.571 on 441 degrees of freedom
## Multiple R-squared:  0.7617, Adjusted R-squared:  0.7547 
## F-statistic: 108.4 on 13 and 441 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="best-subset-regression" class="section level2">
<h2>Best subset regression</h2>
<p>You can use the <code>leaps</code> package to get the best subset regression.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co">#install.packages(&#39;leaps&#39;)</span></span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="kw">library</span>(leaps)</span></code></pre></div>
<pre><code>## Warning: package &#39;leaps&#39; was built under R version 4.0.3</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a>subset_result &lt;-<span class="st"> </span><span class="kw">regsubsets</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>Boston_train, <span class="dt">nbest=</span><span class="dv">2</span>, <span class="dt">nvmax =</span> <span class="dv">14</span>)</span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="kw">plot</span>(subset_result, <span class="dt">scale=</span><span class="st">&quot;bic&quot;</span>)</span></code></pre></div>
<p><img src="Section_07_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Here <code>nbest</code> is the number of subsets of each size to record, and we use <code>2</code> so that each time R compares <code>2</code> variables. <code>nvmax</code> is the maximum size of subsets to examine; this is set to <code>14</code> to consider all the variables in the <code>Boston_train</code> dataset.</p>
<p>Each row represents a model. Black indicates that a variable is included in the model, while white indicates that it is not. The argument <code>scale = ""</code> can be <code>Cp</code>, <code>adjr2</code>, <code>r2</code>, or <code>bic</code>.</p>
<ul>
<li><p>AIC stands for (Akaike’s Information Criteria), a metric developed by the Japanese Statistician, Hirotugu Akaike, 1970. The basic idea of AIC is to penalize the inclusion of additional variables to a model. It adds a penalty that increases the error when including additional terms. <strong>The lower the AIC, the better the model</strong>.</p></li>
<li><p>AICc is a version of AIC corrected for small sample sizes.</p></li>
<li><p>BIC (or Bayesian information criteria) is a variant of AIC with a stronger penalty for including additional variables to the model.</p></li>
<li><p>Mallows Cp: A variant of AIC developed by Colin Mallows.</p></li>
</ul>
<p>What is the problem with the best subset regression? If there are <em>n</em> independent variables, the number of possible nonempty subsets is <span class="math inline">\(2^{n}-1\)</span>. If you try a best subset regression with more than 50 variables, you might need to wait for your entire life to get the result.</p>
</div>
<div id="variable-selection-using-aic" class="section level2">
<h2>Variable Selection Using AIC</h2>
<p>To perform the forward/backward/stepwise regression in R, we need to define the starting points:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>nullmodel=<span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>Boston_train)</span>
<span id="cb41-2"><a href="#cb41-2"></a>fullmodel=<span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>Boston_train)</span></code></pre></div>
<p>The nullmodel is the model with <strong>no</strong> variable in it, while the fullmodel is the model with <strong>every</strong> variable in it.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Backward Elimination</span></span>
<span id="cb42-2"><a href="#cb42-2"></a>model_step_b &lt;-<span class="st"> </span><span class="kw">step</span>(fullmodel,<span class="dt">direction=</span><span class="st">&#39;backward&#39;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=1396.77
## medv ~ crim + zn + indus + chas + nox + rm + age + dis + rad + 
##     tax + ptratio + black + lstat
## 
##           Df Sum of Sq     RSS    AIC
## - indus    1      1.78  9216.7 1394.9
## - age      1     14.11  9229.1 1395.5
## &lt;none&gt;                  9215.0 1396.8
## - chas     1    136.95  9351.9 1401.5
## - tax      1    215.02  9430.0 1405.3
## - zn       1    225.16  9440.1 1405.8
## - crim     1    241.00  9456.0 1406.5
## - black    1    269.20  9484.2 1407.9
## - rad      1    349.63  9564.6 1411.7
## - nox      1    408.91  9623.9 1414.5
## - ptratio  1   1113.20 10328.2 1446.7
## - dis      1   1136.12 10351.1 1447.7
## - lstat    1   1427.68 10642.6 1460.3
## - rm       1   2275.28 11490.2 1495.2
## 
## Step:  AIC=1394.86
## medv ~ crim + zn + chas + nox + rm + age + dis + rad + tax + 
##     ptratio + black + lstat
## 
##           Df Sum of Sq     RSS    AIC
## - age      1     14.06  9230.8 1393.5
## &lt;none&gt;                  9216.7 1394.9
## - chas     1    141.64  9358.4 1399.8
## - zn       1    223.63  9440.4 1403.8
## - crim     1    242.80  9459.5 1404.7
## - tax      1    248.87  9465.6 1405.0
## - black    1    268.00  9484.7 1405.9
## - rad      1    367.72  9584.5 1410.7
## - nox      1    426.25  9643.0 1413.4
## - ptratio  1   1120.71 10337.4 1445.1
## - dis      1   1203.24 10420.0 1448.7
## - lstat    1   1428.27 10645.0 1458.4
## - rm       1   2281.24 11498.0 1493.5
## 
## Step:  AIC=1393.55
## medv ~ crim + zn + chas + nox + rm + dis + rad + tax + ptratio + 
##     black + lstat
## 
##           Df Sum of Sq     RSS    AIC
## &lt;none&gt;                  9230.8 1393.5
## - chas     1    136.72  9367.5 1398.2
## - zn       1    243.10  9473.9 1403.4
## - crim     1    243.47  9474.3 1403.4
## - tax      1    254.35  9485.1 1403.9
## - black    1    263.65  9494.4 1404.4
## - rad      1    386.82  9617.6 1410.2
## - nox      1    513.70  9744.5 1416.2
## - ptratio  1   1149.77 10380.6 1445.0
## - dis      1   1229.68 10460.5 1448.5
## - lstat    1   1750.80 10981.6 1470.6
## - rm       1   2326.12 11556.9 1493.8</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># Forward Selection</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>model_step_f &lt;-<span class="st"> </span><span class="kw">step</span>(nullmodel, <span class="dt">scope=</span><span class="kw">list</span>(<span class="dt">lower=</span>nullmodel, <span class="dt">upper=</span>fullmodel), <span class="dt">direction=</span><span class="st">&#39;forward&#39;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=2023.36
## medv ~ 1
## 
##           Df Sum of Sq   RSS    AIC
## + lstat    1   20679.4 17991 1677.2
## + rm       1   20598.8 18072 1679.2
## + ptratio  1   10532.9 28138 1880.7
## + indus    1    9558.4 29112 1896.2
## + tax      1    8956.1 29715 1905.5
## + nox      1    7106.5 31564 1933.0
## + rad      1    5885.2 32785 1950.2
## + crim     1    5727.8 32943 1952.4
## + age      1    5541.9 33129 1955.0
## + zn       1    5101.4 33569 1961.0
## + black    1    4263.5 34407 1972.2
## + dis      1    2387.9 36283 1996.3
## + chas     1     914.9 37756 2014.5
## &lt;none&gt;                 38671 2023.4
## 
## Step:  AIC=1677.19
## medv ~ lstat
## 
##           Df Sum of Sq   RSS    AIC
## + rm       1    4628.5 13363 1543.9
## + ptratio  1    2925.7 15066 1598.4
## + dis      1     646.0 17345 1662.5
## + chas     1     630.8 17361 1663.0
## + tax      1     451.9 17539 1667.6
## + black    1     255.5 17736 1672.7
## + age      1     204.7 17787 1674.0
## + zn       1     199.7 17792 1674.1
## + crim     1     198.2 17793 1674.2
## + indus    1     188.1 17803 1674.4
## + rad      1      97.3 17894 1676.7
## &lt;none&gt;                 17991 1677.2
## + nox      1       0.1 17991 1679.2
## 
## Step:  AIC=1543.87
## medv ~ lstat + rm
## 
##           Df Sum of Sq   RSS    AIC
## + ptratio  1   1844.75 11518 1478.3
## + tax      1    684.91 12678 1521.9
## + black    1    561.71 12801 1526.3
## + crim     1    448.62 12914 1530.3
## + chas     1    413.07 12950 1531.6
## + rad      1    399.50 12963 1532.1
## + dis      1    197.42 13165 1539.1
## + indus    1    141.25 13222 1541.0
## + zn       1     82.55 13280 1543.0
## &lt;none&gt;                 13363 1543.9
## + nox      1     54.34 13308 1544.0
## + age      1      2.72 13360 1545.8
## 
## Step:  AIC=1478.27
## medv ~ lstat + rm + ptratio
## 
##         Df Sum of Sq   RSS    AIC
## + black  1    437.68 11080 1462.6
## + dis    1    288.15 11230 1468.7
## + chas   1    236.01 11282 1470.8
## + crim   1    204.50 11314 1472.1
## + tax    1    147.84 11370 1474.4
## + nox    1     90.33 11428 1476.7
## &lt;none&gt;               11518 1478.3
## + rad    1     14.99 11503 1479.7
## + indus  1     12.71 11505 1479.8
## + zn     1      7.56 11510 1480.0
## + age    1      1.98 11516 1480.2
## 
## Step:  AIC=1462.64
## medv ~ lstat + rm + ptratio + black
## 
##         Df Sum of Sq   RSS    AIC
## + dis    1    384.20 10696 1448.6
## + chas   1    215.55 10865 1455.7
## + crim   1     86.88 10993 1461.1
## &lt;none&gt;               11080 1462.6
## + tax    1     36.69 11044 1463.1
## + nox    1     26.78 11054 1463.5
## + zn     1     10.99 11069 1464.2
## + rad    1      8.63 11072 1464.3
## + age    1      6.70 11074 1464.4
## + indus  1      0.05 11080 1464.6
## 
## Step:  AIC=1448.59
## medv ~ lstat + rm + ptratio + black + dis
## 
##         Df Sum of Sq   RSS    AIC
## + nox    1    623.20 10073 1423.3
## + indus  1    198.12 10498 1442.1
## + age    1    162.77 10533 1443.6
## + tax    1    162.57 10534 1443.6
## + crim   1    148.86 10547 1444.2
## + chas   1    146.07 10550 1444.3
## + zn     1    132.46 10564 1444.9
## &lt;none&gt;               10696 1448.6
## + rad    1      6.09 10690 1450.3
## 
## Step:  AIC=1423.27
## medv ~ lstat + rm + ptratio + black + dis + nox
## 
##         Df Sum of Sq     RSS    AIC
## + chas   1   177.613  9895.2 1417.2
## + zn     1   135.465  9937.4 1419.1
## + crim   1   101.259  9971.6 1420.7
## + rad    1    58.364 10014.5 1422.6
## &lt;none&gt;               10072.9 1423.3
## + age    1    36.295 10036.6 1423.6
## + indus  1    16.322 10056.5 1424.5
## + tax    1     5.357 10067.5 1425.0
## 
## Step:  AIC=1417.18
## medv ~ lstat + rm + ptratio + black + dis + nox + chas
## 
##         Df Sum of Sq    RSS    AIC
## + zn     1   147.761 9747.5 1412.3
## + crim   1    87.735 9807.5 1415.1
## + rad    1    61.636 9833.6 1416.3
## + age    1    47.417 9847.8 1417.0
## &lt;none&gt;               9895.2 1417.2
## + indus  1    22.808 9872.4 1418.1
## + tax    1     2.036 9893.2 1419.1
## 
## Step:  AIC=1412.33
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn
## 
##         Df Sum of Sq    RSS    AIC
## + crim   1   127.832 9619.7 1408.3
## &lt;none&gt;               9747.5 1412.3
## + rad    1    35.302 9712.2 1412.7
## + age    1    26.590 9720.9 1413.1
## + tax    1    23.059 9724.4 1413.3
## + indus  1    22.973 9724.5 1413.3
## 
## Step:  AIC=1408.33
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim
## 
##         Df Sum of Sq    RSS    AIC
## + rad    1   134.511 9485.1 1403.9
## &lt;none&gt;               9619.7 1408.3
## + age    1    32.120 9587.5 1408.8
## + indus  1    23.637 9596.0 1409.2
## + tax    1     2.046 9617.6 1410.2
## 
## Step:  AIC=1403.92
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim + rad
## 
##         Df Sum of Sq    RSS    AIC
## + tax    1   254.351 9230.8 1393.5
## &lt;none&gt;               9485.1 1403.9
## + indus  1    36.888 9448.3 1404.2
## + age    1    19.543 9465.6 1405.0
## 
## Step:  AIC=1393.55
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim + rad + tax
## 
##         Df Sum of Sq    RSS    AIC
## &lt;none&gt;               9230.8 1393.5
## + age    1   14.0577 9216.7 1394.9
## + indus  1    1.7264 9229.1 1395.5</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># Stepwise Selection </span></span>
<span id="cb46-2"><a href="#cb46-2"></a>model_step_s &lt;-<span class="st"> </span><span class="kw">step</span>(nullmodel, <span class="dt">scope=</span><span class="kw">list</span>(<span class="dt">lower=</span>nullmodel, <span class="dt">upper=</span>fullmodel), <span class="dt">direction=</span><span class="st">&#39;both&#39;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=2023.36
## medv ~ 1
## 
##           Df Sum of Sq   RSS    AIC
## + lstat    1   20679.4 17991 1677.2
## + rm       1   20598.8 18072 1679.2
## + ptratio  1   10532.9 28138 1880.7
## + indus    1    9558.4 29112 1896.2
## + tax      1    8956.1 29715 1905.5
## + nox      1    7106.5 31564 1933.0
## + rad      1    5885.2 32785 1950.2
## + crim     1    5727.8 32943 1952.4
## + age      1    5541.9 33129 1955.0
## + zn       1    5101.4 33569 1961.0
## + black    1    4263.5 34407 1972.2
## + dis      1    2387.9 36283 1996.3
## + chas     1     914.9 37756 2014.5
## &lt;none&gt;                 38671 2023.4
## 
## Step:  AIC=1677.19
## medv ~ lstat
## 
##           Df Sum of Sq   RSS    AIC
## + rm       1    4628.5 13363 1543.9
## + ptratio  1    2925.7 15066 1598.4
## + dis      1     646.0 17345 1662.5
## + chas     1     630.8 17360 1663.0
## + tax      1     451.9 17539 1667.6
## + black    1     255.5 17736 1672.7
## + age      1     204.7 17787 1674.0
## + zn       1     199.7 17792 1674.1
## + crim     1     198.2 17793 1674.2
## + indus    1     188.1 17803 1674.4
## + rad      1      97.3 17894 1676.7
## &lt;none&gt;                 17991 1677.2
## + nox      1       0.1 17991 1679.2
## - lstat    1   20679.4 38671 2023.4
## 
## Step:  AIC=1543.87
## medv ~ lstat + rm
## 
##           Df Sum of Sq   RSS    AIC
## + ptratio  1    1844.8 11518 1478.3
## + tax      1     684.9 12678 1521.9
## + black    1     561.7 12801 1526.3
## + crim     1     448.6 12914 1530.3
## + chas     1     413.1 12950 1531.6
## + rad      1     399.5 12963 1532.1
## + dis      1     197.4 13165 1539.1
## + indus    1     141.3 13222 1541.0
## + zn       1      82.5 13280 1543.0
## &lt;none&gt;                 13363 1543.9
## + nox      1      54.3 13308 1544.0
## + age      1       2.7 13360 1545.8
## - rm       1    4628.5 17991 1677.2
## - lstat    1    4709.2 18072 1679.2
## 
## Step:  AIC=1478.27
## medv ~ lstat + rm + ptratio
## 
##           Df Sum of Sq   RSS    AIC
## + black    1     437.7 11080 1462.6
## + dis      1     288.1 11230 1468.7
## + chas     1     236.0 11282 1470.8
## + crim     1     204.5 11314 1472.1
## + tax      1     147.8 11370 1474.4
## + nox      1      90.3 11428 1476.7
## &lt;none&gt;                 11518 1478.3
## + rad      1      15.0 11503 1479.7
## + indus    1      12.7 11505 1479.8
## + zn       1       7.6 11510 1480.0
## + age      1       2.0 11516 1480.2
## - ptratio  1    1844.8 13363 1543.9
## - lstat    1    3490.2 15008 1596.7
## - rm       1    3547.6 15066 1598.4
## 
## Step:  AIC=1462.64
## medv ~ lstat + rm + ptratio + black
## 
##           Df Sum of Sq   RSS    AIC
## + dis      1     384.2 10696 1448.6
## + chas     1     215.6 10865 1455.7
## + crim     1      86.9 10993 1461.1
## &lt;none&gt;                 11080 1462.6
## + tax      1      36.7 11044 1463.1
## + nox      1      26.8 11054 1463.5
## + zn       1      11.0 11069 1464.2
## + rad      1       8.6 11072 1464.3
## + age      1       6.7 11074 1464.4
## + indus    1       0.1 11080 1464.6
## - black    1     437.7 11518 1478.3
## - ptratio  1    1720.7 12801 1526.3
## - lstat    1    2408.3 13488 1550.1
## - rm       1    3801.5 14882 1594.9
## 
## Step:  AIC=1448.59
## medv ~ lstat + rm + ptratio + black + dis
## 
##           Df Sum of Sq   RSS    AIC
## + nox      1     623.2 10073 1423.3
## + indus    1     198.1 10498 1442.1
## + age      1     162.8 10533 1443.6
## + tax      1     162.6 10534 1443.6
## + crim     1     148.9 10547 1444.2
## + chas     1     146.1 10550 1444.3
## + zn       1     132.5 10564 1444.9
## &lt;none&gt;                 10696 1448.6
## + rad      1       6.1 10690 1450.3
## - dis      1     384.2 11080 1462.6
## - black    1     533.7 11230 1468.7
## - ptratio  1    1812.9 12509 1517.8
## - lstat    1    2782.8 13479 1551.8
## - rm       1    3314.5 14010 1569.4
## 
## Step:  AIC=1423.27
## medv ~ lstat + rm + ptratio + black + dis + nox
## 
##           Df Sum of Sq     RSS    AIC
## + chas     1    177.61  9895.2 1417.2
## + zn       1    135.46  9937.4 1419.1
## + crim     1    101.26  9971.6 1420.7
## + rad      1     58.36 10014.5 1422.6
## &lt;none&gt;                 10072.9 1423.3
## + age      1     36.29 10036.6 1423.6
## + indus    1     16.32 10056.5 1424.5
## + tax      1      5.36 10067.5 1425.0
## - black    1    331.31 10404.2 1436.0
## - nox      1    623.20 10696.1 1448.6
## - dis      1    980.63 11053.5 1463.5
## - lstat    1   1983.88 12056.7 1503.1
## - ptratio  1   2085.87 12158.7 1506.9
## - rm       1   3132.64 13205.5 1544.5
## 
## Step:  AIC=1417.18
## medv ~ lstat + rm + ptratio + black + dis + nox + chas
## 
##           Df Sum of Sq     RSS    AIC
## + zn       1    147.76  9747.5 1412.3
## + crim     1     87.74  9807.5 1415.1
## + rad      1     61.64  9833.6 1416.3
## + age      1     47.42  9847.8 1417.0
## &lt;none&gt;                  9895.2 1417.2
## + indus    1     22.81  9872.4 1418.1
## + tax      1      2.04  9893.2 1419.1
## - chas     1    177.61 10072.9 1423.3
## - black    1    302.87 10198.1 1428.9
## - nox      1    654.75 10550.0 1444.3
## - dis      1    918.59 10813.8 1455.6
## - ptratio  1   1918.44 11813.7 1495.8
## - lstat    1   1950.17 11845.4 1497.0
## - rm       1   3079.48 12974.7 1538.5
## 
## Step:  AIC=1412.33
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn
## 
##           Df Sum of Sq     RSS    AIC
## + crim     1    127.83  9619.7 1408.3
## &lt;none&gt;                  9747.5 1412.3
## + rad      1     35.30  9712.2 1412.7
## + age      1     26.59  9720.9 1413.1
## + tax      1     23.06  9724.4 1413.3
## + indus    1     22.97  9724.5 1413.3
## - zn       1    147.76  9895.2 1417.2
## - chas     1    189.91  9937.4 1419.1
## - black    1    326.43 10073.9 1425.3
## - nox      1    659.11 10406.6 1440.1
## - dis      1   1041.34 10788.8 1456.5
## - ptratio  1   1459.51 11207.0 1473.8
## - lstat    1   2017.23 11764.7 1495.9
## - rm       1   2768.44 12515.9 1524.1
## 
## Step:  AIC=1408.33
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim
## 
##           Df Sum of Sq     RSS    AIC
## + rad      1    134.51  9485.1 1403.9
## &lt;none&gt;                  9619.7 1408.3
## + age      1     32.12  9587.5 1408.8
## + indus    1     23.64  9596.0 1409.2
## + tax      1      2.05  9617.6 1410.2
## - crim     1    127.83  9747.5 1412.3
## - chas     1    174.81  9794.5 1414.5
## - zn       1    187.86  9807.5 1415.1
## - black    1    233.17  9852.8 1417.2
## - nox      1    602.95 10222.6 1434.0
## - dis      1   1114.82 10734.5 1456.2
## - ptratio  1   1252.43 10872.1 1462.0
## - lstat    1   1765.49 11385.1 1483.0
## - rm       1   2831.24 12450.9 1523.7
## 
## Step:  AIC=1403.92
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim + rad
## 
##           Df Sum of Sq     RSS    AIC
## + tax      1    254.35  9230.8 1393.5
## &lt;none&gt;                  9485.1 1403.9
## + indus    1     36.89  9448.3 1404.2
## + age      1     19.54  9465.6 1405.0
## - rad      1    134.51  9619.7 1408.3
## - zn       1    151.77  9636.9 1409.1
## - chas     1    171.42  9656.6 1410.1
## - crim     1    227.04  9712.2 1412.7
## - black    1    289.90  9775.0 1415.6
## - nox      1    735.83 10221.0 1435.9
## - dis      1   1123.84 10609.0 1452.9
## - ptratio  1   1362.44 10847.6 1463.0
## - lstat    1   1795.01 11280.2 1480.8
## - rm       1   2582.02 12067.2 1511.5
## 
## Step:  AIC=1393.55
## medv ~ lstat + rm + ptratio + black + dis + nox + chas + zn + 
##     crim + rad + tax
## 
##           Df Sum of Sq     RSS    AIC
## &lt;none&gt;                  9230.8 1393.5
## + age      1     14.06  9216.7 1394.9
## + indus    1      1.73  9229.1 1395.5
## - chas     1    136.72  9367.5 1398.2
## - zn       1    243.10  9473.9 1403.4
## - crim     1    243.47  9474.3 1403.4
## - tax      1    254.35  9485.1 1403.9
## - black    1    263.65  9494.4 1404.4
## - rad      1    386.82  9617.6 1410.2
## - nox      1    513.70  9744.5 1416.2
## - ptratio  1   1149.77 10380.6 1445.0
## - dis      1   1229.68 10460.5 1448.5
## - lstat    1   1750.80 10981.6 1470.6
## - rm       1   2326.12 11556.9 1493.8</code></pre>
<hr />
</div>
</div>
<div id="in-class-exercises" class="section level1">
<h1>In-class exercises</h1>
<div id="exercise-1" class="section level2">
<h2>Exercise #1</h2>
<p>Please go over the notes once again, make sure you understand the scripts.</p>
</div>
<div id="exercise-2" class="section level2">
<h2>Exercise #2</h2>
<p>2.1 Using the crop yeild data, graphically check crop yeilds in different soil density (<code>density</code>) groups; and conduct a one-way ANOVA test to show whether there is a difference in crop yeild average between soil density (<code>density</code>) group.</p>
<p>2.2 Conduct a two-way ANOVA test to show whether changing the soil density type <strong>or</strong> the blocking method impact the crop yeilds.</p>
</div>
<div id="exercise-3" class="section level2">
<h2>Exercise #3</h2>
<p>In this exercise, we consider CPU performance from different types. Load the data <code>cpus</code> in the <code>MASS</code> package by:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="kw">library</span>(MASS)</span>
<span id="cb48-2"><a href="#cb48-2"></a><span class="kw">data</span>(cpus)</span></code></pre></div>
<p>3.1 Fit a best subset regression between predictor variable <code>perf</code> and response variables <code>syct</code>, <code>mmin</code>, <code>mmax</code>, <code>cach</code>, <code>chmin</code>, <code>chmax</code>. Try <code>bic</code> and <code>adjr2</code> as the <code>scale</code> argument.</p>
<p>3.2 Try forward, backward, and stepwise regression method for variable selection. Compare your best models obtained by the three methods.</p>
<hr />
</div>
</div>
<div id="further-reading" class="section level1">
<h1>Further reading</h1>
<ul>
<li><p><a href="https://daviddalpiaz.github.io/appliedstats/applied_statistics.pdf">Applied Statistics with R</a></p></li>
<li><p><a href="https://bookdown.org/mikemahoney218/LectureBook/basic-statistics-using-r.html">Introduction to Data Exploration and Analysis with R</a></p></li>
<li><p><a href="https://r-statistics.co/">r-statistics</a></p></li>
</ul>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p><a href="https://blog.minitab.com/blog/adventures-in-statistics-2/the-danger-of-overfitting-regression-models">The Danger of Overfitting Regression Models</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p><a href="https://blog.minitab.com/blog/adventures-in-statistics-2/the-danger-of-overfitting-regression-models">The Danger of Overfitting Regression Models</a><a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p><a href="https://xiaoruizhu.github.io/Data-Mining-R/lecture/3_LinearReg.html#compare-model-fit-manually">Regression and Variable Selection</a><a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
